# Generated by Django 4.1.7 on 2024-03-21 05:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="master",
            old_name="macid",
            new_name="mac_id",
        ),
    ]
